# Generated by Django 6.0.6 on 2026-06-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaqEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_darija', models.TextField(verbose_name='Question en Darija')),
                ('keywords', models.CharField(help_text='Ex: cin, carte, identité, renouveler', max_length=255, verbose_name='Mots-clés')),
                ('answer_darija', models.TextField(verbose_name='Réponse simplifiée en Darija')),
                ('legal_reference', models.CharField(help_text='Ex: Dahir n° 1-08-214 du 23 décembre 2008', max_length=255, verbose_name='Référence légale')),
                ('category', models.CharField(choices=[('cin', "Carte Nationale d'Identité"), ('naissance', 'Acte de naissance'), ('location', 'Contrat de location'), ('travail', 'Contrat de travail'), ('tribunal', 'Convocation tribunal'), ('heritage', 'Héritage'), ('cnss', 'CNSS / Sécurité sociale'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Catégorie')),
                ('disclaimer', models.TextField(default='Hada tawjih gha, machi avis juridique officiel.', verbose_name='Avertissement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'FAQ Entry',
                'verbose_name_plural': 'FAQ Entries',
                'ordering': ['category'],
            },
        ),
    ]
