# Generated by Django 6.0.6 on 2026-06-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_file', models.CharField(max_length=500)),
                ('page_number', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('category', models.CharField(default='autre', help_text='Ex: travail, famille, penal, commerce...', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document Juridique',
                'verbose_name_plural': 'Documents Juridiques',
            },
        ),
        migrations.AddField(
            model_name='faqentry',
            name='answer_arabizi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='faqentry',
            name='disclaimer_arabizi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
