# Generated by Django 6.0.6 on 2026-06-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'institution")),
                ('institution_type', models.CharField(choices=[('prefecture', 'Préfecture / Province'), ('commune', 'Commune / Arrondissement'), ('tribunal', 'Tribunal'), ('cnss', 'CNSS'), ('inspection', 'Inspection du Travail'), ('notaire', 'Notaire'), ('autre', 'Autre')], default='autre', max_length=50, verbose_name='Type')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('topics', models.CharField(help_text='Ex: cin, passeport, résidence', max_length=255, verbose_name='Sujets traités')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
                'ordering': ['city', 'name'],
            },
        ),
    ]
